sudo: required
language: node_js
before_install:
  - "npm install"
  - "npm install -g --save-dev babel-cli"
  - "npm install -g --save-dev babel-core"
  - "npm install -g --save-dev babel-preset-es2015"
install:
  - npm run build-js
  - npm run build-js-dev
script:
  - echo "Build successful!"